#!/usr/bin/env bash

export AMAZONSES_HOST="PLACEHOLDER HOST"
export AMAZONSES_USERNAME="PLACEHOLDER USERNAME"
export AMAZONSES_PASSWORD="PLACEHOLDER PASSWORD"
export AMAZONSES_EMAIL_FROM="PLACEHOLDER EMAIL_FROM"
export AMAZONSES_EMAIL_TO="PLACEHOLDER EMAIL_TO"
export AMAZONSES_URL="PLACEHOLDER URL"
